spring:
  application:
    name: spider
  profiles:
    active: @spring.profiles.active@

logging:
  file: ./logs

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 默认deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
---
spring:
  profiles: dev
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/spider_dev?useUnicode=true&character_set_server=utf8mb4&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    connection-test-query: SELECT 1
    pool-name: dr-pool
server:
  port: 8081
  servlet:
    context-path: /spider
logging:
  level:
    com.alibaba.nacos.*: error
    org.springframework.kafka.KafkaListenerEndpointContainer: info

---
spring:
  profiles: prod
server:
  port: 8082
  servlet:
    context-path: /spider
